version: '3'

services:
  wi-room-experience:
    image: jeremywillans/wi-room-experience:latest
    #build: .
    container_name: wi-room-experience
    env_file:
      - .env
    volumes:
      - room-experience-config:/config
    restart: unless-stopped
    networks:
      - internal

volumes:
  room-experience-config:

networks:
  internal:
